### ISSUE TITLE
New version of biopython

### ISSUE THREAD

**Issue by dreyes17** [galaxy-genome-annotation/python-chado#13]
Hello,

Just few months ago Biopython has deleted the Bio.Alphabet module https://biopython.org/wiki/Alphabet. This generate an importError in the file chado/export/__init.py__ . My suggestion is to modify the requirements.txt to have biopython==1.77, and maybe do the same to control the other libraries.

**Comment by hexylena** [comment]
Thanks @dreyes17, that change affected a large number of projects it seems :( 

We can probably work around this without pinning to an outdated biopython.

**Comment by shmenolin** [comment]
This issue still remains and prevents me from making any connection and changes to the database. How would I be able to fix this?

**Comment by hexylena** [comment]
Hi  @BlueGirl15, I opened a PR but I guess we didn't merge it. I'll do that now.

**Comment by hexylena** [comment]
Hey @BlueGirl15 @dreyes17 the new version should be available.
